BelozertsevVS/RDBMS-ED-24-1-2-3

- ЛР 2/KondratievaLW2.sql
> KondratievaLW2

- ЛР 2/IsaievaLW2.sql
> IsaievaLW2

- ЛР 2/SerdiukovLW2.sql
> SerdiukovLW2

- ЛР 1/LysenkoLW1.sql
> LysenkoLW1

- LysenkoLW2.sql
> LysenkoLW2

- ЛР 2/LeshchenkoLW2.sql
> LeshchenkoLW2

- ЛР 2/HolitsynaLW2.sql
> HolitsynaLW2

- ЛР 2/PAFNUTIEVLW2.sql
> PAFNUTIEVLW2

- ЛР 4/IsaievaLW4.sql
> IsaievaLW4

- ЛР 2/NikitenkoLW2.sql
> NikitenkoLW2

- ЛР 4/LeshchenkoLW4.sql
> LeshchenkoLW4

- ЛР 4/LysenkoLW4.sql
> LysenkoLW4

- ЛР 4/NikitenkoLW4.sql
> NikitenkoLW4

- ЛР 4/HorbenkoLW4.sql
> HorbenkoLW4

- ЛР 4/HolitsynaLW4.sql
> HolitsynaLW4

- ЛР 4/BabenkoLW4.sql
> BabenkoLW4

- ЛР 3/KadtsynaLW3(1).sql
> KadtsynaLW3(1)

- ЛР 5/SQLQuery2.sql
> HolitsynaLW5

- ЛР 2/NegretovaLW2.sql
> NegretovaLW2

- ЛР 4/sqlPafnutievBOHDANLW4.sql
> sqlPafnutievBOHDANLW4

- ЛР 6/PafnutievLW6.sql
> PAFNUTIEVLW6

- ЛР 6/LysenkoLW6.sql
> LysenkoLW6

- ЛР 6/LeshchenkoLW6.sql
> LeshchenkoLW6

- ЛР 2/OdincovLW2.sql
> OdincovLW2

- ЛР 3/OdincovLW3.sql
> OdincovLW3

- ЛР 4/BocharovaLW4.sql
> BocharovaLW4

- ЛР 4/BocharovaLW4.sql
- ЛР 5/BocharovaLW5.sql
> BocharovaLW5

- ЛР 6/BocharovaLW6.sql
> BocharovaLW6

- ЛР 5/NegretovaLW5.sql
> NegretovaLW5

- ЛР 6/NegretovaLW6.sql
> NegretovaLW6
